server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3310/authgetway}
    username: ${SPRING_DATASOURCE_USERNAME:auth}
    password: ${SPRING_DATASOURCE_PASSWORD:auth}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: a2668c001@smtp-brevo.com
    password: sFSYxwj8AEZWO610
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    urls:
      - name: jobfinder
        url: /jobs/v3/api-docs
      - name: eventhandler
        url: /events/v3/api-docs
  api-docs:
    enabled: true

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  mail:
    from: simofff0@gmail.com
  use-https: false
  jwt-secret: "mySuperSecretKeyForJWTThatIsAtLeast32CharsLong!!"
  jwt-refresh-secret: "mySuperSecretRefreshKeyThatIsAlsoAtLeast32CharsLong!!"